name:                poitin-grin-frontend
version:             0.1.0.0
github:              "githubuser/Frontend"
license:             BSD3
author:              "Aleksey Tyurin"
maintainer:          "alekseytyurinspb@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Frontend#readme>

dependencies:
- base >= 4.7 && < 5
- distiller
- containers
- grin
- mtl
- transformers
- MissingH
- megaparsec
- text
- tasty
- tasty-hunit
- tasty-hspec

library:
  source-dirs: src
  dependencies:
    - distiller
    - grin

executables:
  poitin-grin-frontend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poitin-grin-frontend
tests:
  poitin-grin-frontend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poitin-grin-frontend
    - tasty
    - tasty-hunit
    - tasty-hspec